#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tests that column BEHAVIOUR is carried, not just column definitions.

The defect: the translator carried NOT NULL and dropped every DEFAULT, which is
a worse combination than dropping both. `NOT NULL DEFAULT 0` arrived as bare
`NOT NULL` -- the constraint without the thing that satisfies it -- so the
destination was STRICTER than the source and every insert omitting the column
failed. All four declared defaults in the live card store were lost that way,
found only by hitting them one write at a time on a real database.

`dflt_value` was never read from PRAGMA at all, so nothing downstream could have
reported it however careful it was.

Second instance, same family: an `INTEGER PRIMARY KEY` is a rowid alias that
SQLite auto-assigns, so the application never supplies it. Carried without an
identity, the table is READ-ONLY IN PRACTICE while looking healthy.

Real SQLite throughout. No mocks. One assertion per test, AAA markers.
"""

from __future__ import annotations

import os
import shutil
import sqlite3
import tempfile

import pytest

from scitex_db._migrate._ddl import Column, create_table_ddl
from scitex_db._migrate._introspect import connect_readonly, read_columns
from scitex_db._migrate._preflight import preflight
from scitex_db._migrate._plan import Disposition, TablePlan


@pytest.fixture
def workspace():
    tmpdir = tempfile.mkdtemp()
    yield tmpdir
    shutil.rmtree(tmpdir, ignore_errors=True)


def _store(tmpdir, ddl, name="s.db"):
    path = os.path.join(tmpdir, name)
    conn = sqlite3.connect(path)
    conn.execute(ddl)
    conn.commit()
    conn.close()
    return path


@pytest.fixture
def carded(workspace):
    """The shape that lost its defaults on the live store."""
    return _store(
        workspace,
        "CREATE TABLE tasks ("
        "  id TEXT PRIMARY KEY,"
        "  revision INTEGER NOT NULL DEFAULT 0,"
        "  status TEXT DEFAULT 'pending'"
        ")",
    )


def _columns(path, table):
    conn = connect_readonly(path)
    try:
        return read_columns(conn, table)
    finally:
        conn.close()


def test_a_declared_default_is_read_from_the_source(carded):
    # It used not to be read at all, which is why nothing could report it.
    # Arrange
    columns = _columns(carded, "tasks")
    # Act
    revision = next(c for c in columns if c.name == "revision")
    # Assert
    assert revision.default_expr == "0"


def test_a_column_without_a_default_reports_none(carded):
    # `None` must mean "genuinely has none", not "we did not look".
    # Arrange
    columns = _columns(carded, "tasks")
    # Act
    id_col = next(c for c in columns if c.name == "id")
    # Assert
    assert id_col.default_expr is None


def test_a_literal_default_is_carried_into_the_ddl(carded):
    # Arrange
    columns = _columns(carded, "tasks")
    # Act
    ddl = create_table_ddl("tasks", columns)
    # Assert
    assert "DEFAULT 0" in ddl


def test_a_quoted_literal_default_is_carried_into_the_ddl(carded):
    # Arrange
    columns = _columns(carded, "tasks")
    # Act
    ddl = create_table_ddl("tasks", columns)
    # Assert
    assert "DEFAULT 'pending'" in ddl


def test_the_not_null_constraint_is_still_carried(carded):
    # The fix must not trade one half of the pair for the other.
    # Arrange
    columns = _columns(carded, "tasks")
    # Act
    ddl = create_table_ddl("tasks", columns)
    # Assert
    assert "NOT NULL" in ddl


def test_an_expression_default_is_not_translated():
    # Guessing the PostgreSQL spelling of a SQLite expression invents behaviour.
    # Arrange
    col = Column("made", "TEXT", default_expr="CURRENT_TIMESTAMP")
    # Act
    ddl = create_table_ddl("t", [col])
    # Assert
    assert "CURRENT_TIMESTAMP" not in ddl


def test_an_integer_primary_key_becomes_an_identity(workspace):
    # The task_comments defect: SQLite auto-assigns it, PostgreSQL will not.
    # Arrange
    path = _store(workspace, "CREATE TABLE c (id INTEGER PRIMARY KEY, t TEXT)")
    columns = _columns(path, "c")
    # Act
    ddl = create_table_ddl("c", columns)
    # Assert
    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl


def test_a_text_primary_key_does_not_become_an_identity(workspace):
    # NEGATIVE CASE. Inventing an identity the source never had is its own bug.
    # Arrange
    path = _store(workspace, "CREATE TABLE c (id TEXT PRIMARY KEY, t TEXT)")
    columns = _columns(path, "c")
    # Act
    ddl = create_table_ddl("c", columns)
    # Assert
    assert "IDENTITY" not in ddl


def test_a_composite_integer_key_is_not_a_rowid_alias(workspace):
    # `INTEGER PRIMARY KEY` aliases the rowid only on a single-column key.
    # Arrange
    path = _store(
        workspace,
        "CREATE TABLE c (a INTEGER, b INTEGER, PRIMARY KEY (a, b))",
    )
    columns = _columns(path, "c")
    # Act
    aliases = [c.name for c in columns if c.rowid_alias]
    # Assert
    assert aliases == []


def test_a_bigint_primary_key_is_not_a_rowid_alias(workspace):
    # The spelling is load-bearing: only `INTEGER` aliases the rowid.
    # Arrange
    path = _store(workspace, "CREATE TABLE c (id BIGINT PRIMARY KEY)")
    columns = _columns(path, "c")
    # Act
    aliases = [c.name for c in columns if c.rowid_alias]
    # Assert
    assert aliases == []


@pytest.fixture
def unsatisfiable(workspace):
    """NOT NULL whose default is an expression we will not carry."""
    path = _store(
        workspace,
        "CREATE TABLE tasks ("
        "  id TEXT PRIMARY KEY,"
        "  made TEXT NOT NULL DEFAULT (datetime('now'))"
        ")",
    )
    return preflight(
        path, {"tasks": TablePlan("tasks", Disposition.MIGRATE)}
    )


def test_a_not_null_column_losing_its_default_blocks(unsatisfiable):
    # The constraint would arrive without the thing that satisfies it.
    # Arrange
    report = unsatisfiable
    # Act
    verdict = report.ok
    # Assert
    assert verdict is False


def test_the_blocker_names_the_column(unsatisfiable):
    # Arrange
    report = unsatisfiable
    # Act
    text = report.summary()
    # Assert
    assert "'made'" in text


@pytest.fixture
def merely_lossy(workspace):
    """A NULLABLE column losing its default -- reported, but not a blocker."""
    path = _store(
        workspace,
        "CREATE TABLE tasks ("
        "  id TEXT PRIMARY KEY,"
        "  made TEXT DEFAULT (datetime('now'))"
        ")",
    )
    return preflight(
        path, {"tasks": TablePlan("tasks", Disposition.MIGRATE)}
    )


def test_a_nullable_column_losing_its_default_does_not_block(merely_lossy):
    # Lossy is not broken: inserts still succeed, they just land NULL.
    # Collapsing the two would block migrations that are merely lossy.
    # Arrange
    report = merely_lossy
    # Act
    verdict = report.ok
    # Assert
    assert verdict is True


def test_a_nullable_column_losing_its_default_is_still_reported(merely_lossy):
    # Silently dropping it is indistinguishable from never having had one.
    # Arrange
    report = merely_lossy
    # Act
    dropped = report.tables[0].undefaulted
    # Assert
    assert dropped == (("made", "datetime('now')"),)

# EOF
