"""Cross-package import gate (PS-140) for scitex-db.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.
Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-db --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).

The AAA marker comments in the test body below are NOT as the
generator emits them. As of scitex-dev 0.41.1 the generator writes a
combined `# Arrange / Act` marker, which its own PA-307 / STX-TQ002
rule rejects ("each of `# Arrange`, `# Act`, `# Assert` must appear on
its own line in order") -- so a freshly generated gate fails the audit
it was generated to pass. Split here to satisfy the rule. Re-running
the generator will reintroduce the violation until that is fixed
upstream; re-split the markers if so. The LIST above is untouched.
"""

import importlib

import pytest

CROSS_PACKAGE_IMPORTS = [
    'scitex',
    'scitex_dev._cli._completion',
    'scitex_dev.linter._rules._base',
    'scitex_dev.linter.checker',
]


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves(module_name):
    # Arrange: nothing to build — the module name is the parametrised input
    # Act: a real import, not importlib.util.find_spec. find_spec only proves
    # a module is FINDABLE on the path, and the failures this gate exists to
    # catch (a renamed symbol re-exported through a package __init__) happen
    # at EXECUTION.
    module = importlib.import_module(module_name)

    # Assert
    assert module is not None
