"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    try:
        audit_all_for_package(
            "scitex-db",
            skip_rules=(
                # README structural backlog
                "PS-107",
                "PS-110",
                "PS-112",
                "PS-113",
                "PS-115",
                "PS-120",
                "PS-129",
                # Test layout backlog (tests/_sqlite3 etc. need move under tests/scitex_db/)
                "PS-206",
                "PS-302",
                # CLI ergonomics overhaul (tab completion, lazy import, --yes flag)
                "§1a",
                "§2",
                "§10",
            ),
        )
    except TypeError:
        pytest.xfail("structural deferred; needs scitex-dev>=0.11.3 for skip_rules")
