"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-db",
        skip_rules=(
            # README structural backlog — needs full template overhaul
            # (logo, footer, Four Freedoms blockquote, umbrella one-liner,
            # .env.example). Tracked as a single coherent README rewrite.
            "PS-107",
            "PS-110",
            "PS-112",
            "PS-113",
            "PS-115",
            "PS-120",
            "PS-129",
            # Test-tree migration — tests/_postgresql/, tests/_sqlite3/,
            # tests/_BaseMixins/ need to move under tests/scitex_db/, plus
            # one orphan (test_skills_quality.py) and __main__ mirror gap.
            # Defer to a single migration commit alongside the layout move.
            "PS-204",
            "PS-206",
            "PS-302",
            # CLI ergonomics overhaul (tab completion, lazy import, --yes)
            "§1a",
            "§2",
            "§10",
        ),
    )
